FROM node:21 AS builder
WORKDIR /app
COPY . .
ENV REACT_APP_URL=https://staging.e12test.com/api
RUN npm install
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html/ogrenci
RUN rm -rf ./*
COPY --from=builder /app/build .
COPY nginx-staging.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]